version: '3'
services:
  #APP SERVICES
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: Backend-lsp
    restart: unless-stopped
    ports:
      - '14045:1921'
    networks:
      - website-discord-kelbuk_default

networks:
  website-discord-kelbuk_default:
    external: true
